CosmosContracts/juno-tools

package.json
yarn.lock

While this is not included in the tickets, this PR enforces specific ESLint rules to ensure consistency in code formatting and imports/exports.
**This is very opinionated, discussion is advised.**
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/8220954/153077124-b7a490dd-28b8-467d-82ba-4c0da91f1036.png)|![image](https://user-images.githubusercontent.com/8220954/153077163-50ccd3ae-d3d4-4eef-9854-69cf9ff16e23.png)|
- run `yarn lint`
- https://github.com/prettier/eslint-plugin-prettier
- https://github.com/lydell/eslint-plugin-simple-import-sort

feat(eslint): update configuration

---

package.json
yarn.lock

This PR adds `eslint-plugin-tailwindcss` for sorting tailwind classnames to ensure consistency throughout the codebase.
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/8220954/153898934-09fd1c25-8d80-4537-8dd7-7c8bd3a63883.png)|![image](https://user-images.githubusercontent.com/8220954/153898968-d72cbde2-abab-4f76-9ffd-222626a48e77.png)|
- add/edit/delete any tailwind classname on any component/page
- format/lint using eslint
\-

feat(eslint): add eslint-plugin-tailwindcss

---

styles/globals.css

This PR removes an unused stylesheet import for a previously used font family.
\-
\-
\-
\-

fix(styles): remove unused css import

---

components/SidebarContainer.tsx
components/SidebarLayout.tsx
styles/globals.css

This PR fixes #31 and other sidebar related regression issues.
\-

fix(ui): resolve sidebar issues

---

pages/index.tsx

Fixes #37
This PR hides lorem ipsum copies on the home page.
\-

feat(pages): update home page copy text

---

.husky/pre-commit
package.json
yarn.lock

Fixes #21
This PR replaces current pre-commit workflow with [`husky`](https://github.com/typicode/husky) and [`lint-staged`](https://github.com/okonet/lint-staged).
In short, rather than running precommit on all files, only staged files will be cleaned up by either `prettier` or `eslint` depending on the `lint-staged` rulesets defined inside `package.json`.
\-
- https://github.com/typicode/husky
- https://github.com/okonet/lint-staged

refactor: integrate husky and lint-staged

---

components/Layout.tsx

Fixes #38
This PR adds a blocker notice on small viewports.
\-
\-

feat(ui): add notice on small viewports

---

components/DefaultAppSeo.tsx
components/Layout.tsx
config/meta.ts
package.json
pages/airdrops/[address]/claim.tsx
pages/airdrops/create.tsx
pages/airdrops/fund.tsx
pages/airdrops/index.tsx
pages/airdrops/list.tsx
pages/airdrops/manage.tsx
pages/airdrops/register.tsx
yarn.lock

Partially fixes #9
This PR adds default SEO values and pages titles throughout airdrop pages.
\-

feat(pages): improve seo

---

components/AirdropsStepper.tsx
pages/airdrops/create.tsx

Resolve #50
This PR creates an `<AirdropsStepper />` component to navigate between airdrop creation pages.
\-

feat(ui): create airdrops stepper component

---

components/JsonPreview.tsx
pages/airdrops/create.tsx
pages/airdrops/register.tsx

This PR updates the airdrops register page styling.
- copy an airdrop address from `/airdrops` and test in `/airdrops/register`
\-
[^1]: See #58 and #66

refactor(pages): update airdrops register page styling

---

components/Radio.tsx
components/Stats.tsx
pages/airdrops/create.tsx
pages/airdrops/fund.tsx

This PR updates the airdrops fund page.
- copy an airdrop address from `/airdrops` and test in `/airdrops/fund`
Add links to Figma files, documentation, etc.
[^1]: See #58 and #66

refactor(pages): rework airdrops fund page

---

components/AirdropEscrowStatus.tsx
components/AirdropStatus.tsx
components/Alert.tsx
components/Conditional.tsx
components/StackedList.tsx
pages/airdrops/escrow.tsx
utils/constants.ts
utils/text.ts

Fixes #87
This hefty PR reworks the escrow page including various UI elements regarding escrow notice in airdrops fund and register page.
**Initial escrow page**
**Incomplete escrow**
**Processing escrow**
**Intercepted browser close when escrow is processing**
**Completed escrow**
- use existing cw20 to create airdrop
- proceed to escrow step as usual
- ...
\-

refactor(pages): rework airdrop escrow page

---

env.d.ts
pages/airdrops/fund.tsx
pages/airdrops/success.tsx

Fixes #65
This PR implements an airdrop success page for after funding an airdrop is finished.
\-

feat(pages): create airdrop success page

---

contracts/cw20/base/contract.ts
pages/airdrops/[address]/claim.tsx

Fixes #104
This PR reworks the airdrop claim page.
**Loading**
**Not claimed**
**Claimed**
**No allocation**
- Check various airdrops with different states (unclaimable, claimed, etc.)
\-

refactor(pages): rework airdrop claim page

---

hooks/useDevAssignWindow.ts

This PR adds a dev-only hook to assign any custom value in `window`, meaning it will only run in development mode.
- https://github.com/CosmosContracts/juno-tools/pull/106#issue-1177292495
- register state setters in `window`
```js
const [count, setCount] = useState(0)
useDevAssignWindow({ setCount })
```
- open browser console and use state setter in `window`
```js
window.setCount(1)
```
- make sure in production build that given property is not assigned in `window`
\-

feat(hooks): add useDevAssignWindow hook

---

components/InputDateTime.tsx

Fixes #61
This PR resolves #61 by overriding the default date time icon buttons.
- http://localhost:3000/airdrops/create/
\-

feat(ui): override default datetime icons

---

components/AirdropsStepper.tsx

Fixes #105
This PR updates the airdrops stepper styling to improve a11y on active step.
- open any airdrop create step page
\-

fix(ui): update airdrops stepper color

---

components/Layout.tsx

Fixes #120
This PR resolves #120 by adding another wrapper for layout max-width.
- open any page with long contents and make sure the scroll bar is at the rightmost screen
\-

fix(ui): use extra wrapper for layout max-width

---

components/WalletLoader.tsx

This PR removes a useless fragment component in wallet loader.
**Before removing fragment console error**
\-
\-

fix(ui): remove useless wallet loader fragment

---

config/keplr.ts
config/network.ts

Keplr Wallet doesn't like having duplicate currencies (i.e., feeToken: ujunox, stakingToken: ujunox) anymore.
The issue affects newcomers adding the uni testnet to their list of chains for the first time.

Fix keplr wallet connection issue & update testnet chainId
