CosmosContracts/juno-tools

next.config.js
package.json
pages/index.tsx
yarn.lock

This PR adds the new brand logo in home page, [which includes adding SVGR support](https://react-svgr.com/docs/next/).
\-
[Add links to Figma files, documentation, etc.](https://www.figma.com/file/ajr8SLkAaA08upoIMp6bds/?node-id=129%3A338)

feat(pages): add brand logo in home page

---

pages/airdrops/create.tsx
utils/isValidAirdropFile.ts

Calculating total amount using the accounts fields is a better approach since people are putting incorrect values in the file

airdrop total amount calculation

---

tailwind.config.js

Resolves #14
This PR adds additional colors on tailwind color tokens.
\-
\-
\-

chore(tailwind): update colors

---

contexts/contracts.tsx
contexts/theme.tsx
contexts/wallet.tsx
contracts/cw1/subkeys/contract.ts
contracts/cw1/subkeys/useContract.ts
contracts/cw20/base/contract.ts
contracts/cw20/base/useContract.ts
contracts/cw20/bonding/contract.ts
contracts/cw20/bonding/useContract.ts
contracts/cw20/staking/contract.ts
contracts/cw20/staking/useContract.ts
package.json
pages/_document.tsx
pages/airdrops/[address]/claim.tsx
pages/airdrops/create.tsx
pages/airdrops/fund.tsx
pages/airdrops/index.tsx
pages/airdrops/list.tsx
pages/airdrops/manage.tsx
pages/airdrops/register.tsx
services/keplr.ts
utils/debounce.ts
utils/isValidAirdropFile.ts

This PR runs `yarn lint` which cleans up imports and other lints.
\-
\-
\-

chore: lint cleanup

---

pages/airdrops/list.tsx

Pagination logic for trying out the new testnet version. 
The backend code is not deployed yet so this might not work for now. Going to deploy the server code tomorrow morning to test out this feature.
This will be replaced by the infinite scroll logic.

Airdrops List Pagination

---

components/AirdropsStartEndRadio.tsx
components/FormControl.tsx
components/Input.tsx
components/InputDateTime.tsx
env.d.ts
pages/airdrops/create.tsx
styles/datepicker.css
utils/links.ts

Fixes #57
This week-long PR updates the create airdrop page according to the Figma spec.
https://cdn.discordapp.com/attachments/933515307597848656/947554886529196072/junotools-create-airdrop-page-2022-02-28.gif
- ensure all inputs are fillable and clickable
- try both click to upload csv and drag file to input area
\-

refactor(pages): rework airdrops create page

---

components/Layout.tsx

Closes #76
This PR adds a max-width for the app layout.
- open any page and make sure the content does not stretch the whole window
\-

feat(ui): set layout max width

---

components/AirdropsTable.tsx
components/AnchorButton.tsx
components/Button.tsx
pages/airdrops/[address]/claim.tsx
pages/airdrops/create.tsx
pages/airdrops/escrow.tsx
pages/airdrops/fund.tsx
pages/airdrops/list.tsx
pages/airdrops/register.tsx

Fixes #70
This PR creates a Button and AnchorButton element to be reused in various pages.
TODO
- open existing pages with buttons and see if there are different behaviors
\-

feat(ui): extract button components

---

components/FormControl.tsx
components/FormGroup.tsx
components/Input.tsx
components/LinkTab.tsx
components/LinkTabs.data.ts
components/LinkTabs.tsx
components/PageHeader.tsx
components/PageHeaderCW20.tsx
components/Sidebar.tsx
hooks/useInstantiateCW20Form.ts
package.json
pages/contracts/cw20/execute.tsx
pages/contracts/cw20/index.tsx
pages/contracts/cw20/instantiate.tsx
pages/contracts/cw20/query.tsx
utils/cw20.ts
utils/links.ts
yarn.lock

Fixes #100 💯
This PR implements CW20 contract pages for instantiate, query, and execute.
**Instantiate (WIP)**
**Query**
- create cw20 token from instantiate page
- test cw20 in query page
- initiate cw20 contract executions in execute page
\-

feat(pages): implement cw20 pages

---

components/Modal.tsx
components/Radio.tsx
pages/_app.tsx

Add disclaimer modal

---

env.d.ts
pages/sign-verify.tsx
tailwind.config.js
utils/constants.ts

Adding send tweet button in sign-verify page

---

components/WalletButton.tsx
components/WalletLoader.tsx
components/WalletPanelButton.tsx
package.json
yarn.lock

Fixes #93, need #129 to be merged.
This chonker PR reworks the wallet button using #129.
- try connect and disconnect wallet on sidebar
\-

refactor(ui): rework wallet loader component

---

contexts/contracts.tsx
contexts/wallet.tsx

Continuing #129
This PR adds some jsdocs in contracts ctx and wallet ctx to explain the recent #129 changes.
\-
\-

feat(ctx): add contracts and wallet ctx docs

---

contexts/sidebar.ts

This PR removes sidebar state persisting due to SSR issues.
\-
- opening and closing sidebar should be as usual
- refresh page should keep sidebar open
\-

chore(ctx): remove sidebar persist

---

yarn.lock

This PR bumps all package versions according to their semver ranges.
\-
- app should work as usual with no changes
\-

chore(deps): bump versions

---

components/DefaultAppSeo.tsx
next.config.js
package.json
utils/constants.ts

Fixes #128
This PR fixes the twitter card image with website url and also improving DX for env handling and website url resolving.
\-
- technically after merged, test image url with https://cards-dev.twitter.com/validator
\-

fix(ui): prefix twitter card image with website url

---

components/AirdropsTable.tsx
pages/airdrops/list.tsx
utils/airdrop.ts
utils/text.ts

This PR does quality of life improvements for the airdrop list page.
- open airdrops list page and make sure previous behaviors are the same
\-

feat(pages): improve airdrop list page

---

pages/contracts/cw20/query.tsx
utils/cw20.ts

feat(pages): add address inputs for cw20 queries

---

components/Anchor.tsx
package.json
yarn.lock

This PR upgrade all dependencies and bump to React 18.
\-
- Make sure running dev server and build script works
Add links to Figma files, documentation, etc.
\-

feat(deps): upgrade all dependencies

---

config/favicons.json

Fix typo in metadata
Added 'army' to "swiss knife"

chore(config): update metadata description

---

contracts/cw20/base/contract.ts
pages/contracts/cw20/execute.tsx
utils/cw20/execute.ts

- Added mint message to cw20 base execute messages
- Refactored cw20 base execute transaction message previews

Sync development to testnet

---

pages/contracts/cw721/base/execute.tsx
pages/contracts/cw721/base/query.tsx

chore(pages): fix typo in cw721 execute page

---

README.md
pages/contracts/cw20/base/execute.tsx
pages/contracts/cw20/base/instantiate.tsx
pages/contracts/cw20/base/query.tsx
pages/contracts/upload.tsx
utils/links.ts

- Fixed a dead CW-20 docs link 
- Updated readme docs links
- Renamed **Docs CW-20** reference to **Docs CW-20 Base** for consistency with others

fix dead links

---

pages/index.tsx

* Changed "swiss knife" to "Swiss Army knife"
* Removed unnecessary / unconventional "as" before "Smart Contract Dashboard"
* Changed "and" to "to" for style because "and" is used a couple words later in the same sentence
* Capitalized first letter of "Airdrops" and "Create Airdrop" page names
* Changed reference to Create Airdrop page to include the page name
Fixes #<ISSUE_NUMBER>
Describe big picture changes here. This will give viewers context for the changes.
Add links to Figma files, documentation, etc.

Typo fixes

---

pages/sign-verify.tsx

Fixes #<ISSUE_NUMBER>
I felt the need to explain a little more to basic users about what sign and verify can do. More descriptive placeholders on what to write as an example now provided. I will do a video on a use case for this in the coming week or so as i think this is an awesome tool.
Added some placeholders for Sign and Verify contract

Sign and verify placeholder

---

utils/isValidAccountsFile.ts

The user is alerted about the presence of duplicate addresses in the .csv file.

Check for duplicate addresses in the uploaded .csv file during Airdrop creation

---

contracts/cw20/merkleAirdrop/contract.ts
contracts/cw20/merkleAirdrop/useContract.ts
pages/airdrops/[address]/claim.tsx
pages/airdrops/create.tsx
pages/airdrops/fund.tsx
utils/constants.ts

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202471321819201

Native token airdrop support

---

components/AirdropStatus.tsx
components/AirdropsStepper.tsx
contracts/cw20/merkleAirdrop/contract.ts
pages/airdrops/create.tsx
pages/airdrops/manage.tsx
pages/airdrops/register.tsx

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202471322019142
- https://app.asana.com/0/0/1202471322019154

Manage (burn or withdraw) remaining funds for an expired airdrop

---

components/AirdropStatus.tsx
components/AirdropsStepper.tsx
components/AirdropsTable.tsx
contracts/cw20/merkleAirdrop/contract.ts
contracts/cw20/merkleAirdrop/useContract.ts
next.config.js
package.json
pages/_app.tsx
pages/airdrops/[address]/claim.tsx
pages/airdrops/create.tsx
pages/airdrops/fund.tsx
pages/airdrops/manage.tsx
pages/airdrops/register.tsx
utils/constants.ts
utils/isValidAccountsFile.ts
yarn.lock

- Added terra address support for airdrops https://github.com/CosmosContracts/juno-tools/pull/224
- Added airdrops native token support https://github.com/CosmosContracts/juno-tools/pull/220
- Added manage page for airdrops https://github.com/CosmosContracts/juno-tools/pull/223
- Added integer checking for airdrop whitelist amounts https://github.com/CosmosContracts/juno-tools/pull/218
- Fixed some typos https://github.com/CosmosContracts/juno-tools/pull/219

Merge testnet to main

---

contracts/cw20/merkleAirdrop/contract.ts
package.json
pages/airdrops/[address]/claim.tsx
pages/contracts/upload.tsx

- Add ledger support for terra airdrops https://github.com/CosmosContracts/juno-tools/pull/241
- Add connected wallet check for contract uploads https://github.com/CosmosContracts/juno-tools/pull/246

Sync testnet to main

---

components/AirdropsTable.tsx
contracts/cw20/merkleAirdrop/contract.ts
pages/airdrops/manage.tsx

Feature: Pause/Resume Airdrop
